//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LED_EPL.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAIXOTE_EPL
    {
        public int id { get; set; }
        public string id_pallet { get; set; }
        public string sn { get; set; }
        public string modelo { get; set; }
        public string ckd { get; set; }
        public string linha { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> datahora { get; set; }
        public string filial { get; set; }
    }
}
