//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LED_EPL.Class
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPLEntitiesModel_User : DbContext
    {
        public EPLEntitiesModel_User()
            : base("name=EPLEntitiesModel_User")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MODELO_EPL> MODELO_EPL { get; set; }
        public virtual DbSet<OP_EPL> OP_EPL { get; set; }
        public virtual DbSet<CAIXOTE_EPL> CAIXOTE_EPL { get; set; }
        public virtual DbSet<USERS_EPL> USERS_EPL { get; set; }
    }
}
