//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LED_EPL.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELO_EPL
    {
        public int id { get; set; }
        public string modelo { get; set; }
        public string descricao { get; set; }
        public Nullable<int> qtd_painel { get; set; }
        public string familia { get; set; }
    }
}
