//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LED_EPL.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_EPL
    {
        public string ckd { get; set; }
        public int modelo_id_fk { get; set; }
        public string status_op { get; set; }
        public System.DateTime data { get; set; }
        public System.DateTime data_hora { get; set; }
        public int qtd { get; set; }
        public Nullable<int> qtd_atual { get; set; }
        public string ordem { get; set; }
        public int user_id { get; set; }
        public string filial { get; set; }
        public string description { get; set; }
    }
}
