//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LED_EPL.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_EPL
    {
        public int matricula { get; set; }
        public string nome { get; set; }
        public string senha { get; set; }
        public string setor { get; set; }
        public string funcao { get; set; }
        public Nullable<int> status_user { get; set; }
        public Nullable<int> producao { get; set; }
        public Nullable<int> ckd { get; set; }
        public Nullable<int> caixote { get; set; }
        public Nullable<int> adm { get; set; }
    }
}
